# Generated by Django 5.2 on 2025-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField()),
                ('timezones', models.TextField()),
                ('region', models.CharField(max_length=50)),
                ('languages', models.TextField(blank=True)),
                ('flag_url', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
