# Generated by Django 5.2.1 on 2025-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='country',
            name='timezones',
            field=models.JSONField(default=list),
        ),
    ]
